version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: codebase_rag_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme}
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - codebase_rag_network
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 0.5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: codebase_rag_redis_commander
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-changeme}
    networks:
      - codebase_rag_network
    profiles:
      - debug

volumes:
  redis_data:
    driver: local

networks:
  codebase_rag_network:
    driver: bridge
